/**
 * AUTO-GENERATED by `bun alea trading:gen-probability-table`.
 *
 * Do not edit by hand. Re-run the command to refresh; the live trader
 * loads this exact value at boot, so a stale table here means a stale
 * model in production.
 */

import type { ProbabilityTable } from "@alea/lib/trading/types";

export const probabilityTable: ProbabilityTable = {
  "command": "trading:gen-probability-table",
  "schemaVersion": 1,
  "generatedAtMs": 1778438561087,
  "series": {
    "source": "pyth",
    "product": "spot",
    "timeframe": "5m"
  },
  "minBucketSamples": 200,
  "trainingRangeMs": {
    "firstWindowMs": 1715194740000,
    "lastWindowMs": 1778333160000
  },
  "assets": [
    {
      "asset": "btc",
      "windowCount": 210389,
      "leadingTables": [
        {
          "algoId": "vol_only_3",
          "regime": "low_vol",
          "windowShare": 0.04171796053976206,
          "avgLeadPp": 5.926205643994201,
          "surface": {
            "byRemaining": {
              "1": [
                {
                  "distanceBp": 2,
                  "samples": 1053,
                  "probability": 0.8822412155745489
                },
                {
                  "distanceBp": 3,
                  "samples": 976,
                  "probability": 0.9170081967213115
                },
                {
                  "distanceBp": 4,
                  "samples": 750,
                  "probability": 0.9333333333333333
                },
                {
                  "distanceBp": 5,
                  "samples": 613,
                  "probability": 0.9477977161500816
                },
                {
                  "distanceBp": 6,
                  "samples": 482,
                  "probability": 0.9605809128630706
                },
                {
                  "distanceBp": 7,
                  "samples": 364,
                  "probability": 0.978021978021978
                },
                {
                  "distanceBp": 8,
                  "samples": 303,
                  "probability": 0.9735973597359736
                },
                {
                  "distanceBp": 9,
                  "samples": 248,
                  "probability": 0.967741935483871
                },
                {
                  "distanceBp": 10,
                  "samples": 213,
                  "probability": 0.9953051643192489
                }
              ],
              "2": [
                {
                  "distanceBp": 2,
                  "samples": 1149,
                  "probability": 0.7798085291557877
                },
                {
                  "distanceBp": 3,
                  "samples": 932,
                  "probability": 0.8562231759656652
                },
                {
                  "distanceBp": 4,
                  "samples": 767,
                  "probability": 0.8683181225554107
                },
                {
                  "distanceBp": 5,
                  "samples": 617,
                  "probability": 0.8962722852512156
                },
                {
                  "distanceBp": 6,
                  "samples": 441,
                  "probability": 0.9319727891156463
                },
                {
                  "distanceBp": 7,
                  "samples": 358,
                  "probability": 0.946927374301676
                },
                {
                  "distanceBp": 8,
                  "samples": 250,
                  "probability": 0.908
                }
              ],
              "3": [
                {
                  "distanceBp": 2,
                  "samples": 1208,
                  "probability": 0.7466887417218543
                },
                {
                  "distanceBp": 3,
                  "samples": 957,
                  "probability": 0.7857889237199582
                },
                {
                  "distanceBp": 4,
                  "samples": 712,
                  "probability": 0.8328651685393258
                },
                {
                  "distanceBp": 5,
                  "samples": 494,
                  "probability": 0.8137651821862348
                },
                {
                  "distanceBp": 6,
                  "samples": 377,
                  "probability": 0.8620689655172413
                },
                {
                  "distanceBp": 7,
                  "samples": 244,
                  "probability": 0.8934426229508197
                },
                {
                  "distanceBp": 8,
                  "samples": 210,
                  "probability": 0.8952380952380953
                }
              ],
              "4": [
                {
                  "distanceBp": 2,
                  "samples": 1285,
                  "probability": 0.7050583657587549
                },
                {
                  "distanceBp": 3,
                  "samples": 758,
                  "probability": 0.7084432717678101
                },
                {
                  "distanceBp": 4,
                  "samples": 525,
                  "probability": 0.7409523809523809
                },
                {
                  "distanceBp": 5,
                  "samples": 348,
                  "probability": 0.7758620689655172
                },
                {
                  "distanceBp": 6,
                  "samples": 222,
                  "probability": 0.7657657657657657
                }
              ]
            }
          }
        }
      ]
    },
    {
      "asset": "eth",
      "windowCount": 210399,
      "leadingTables": [
        {
          "algoId": "vol_only_3",
          "regime": "low_vol",
          "windowShare": 0.024543842888987116,
          "avgLeadPp": 6.373971450638126,
          "surface": {
            "byRemaining": {
              "1": [
                {
                  "distanceBp": 2,
                  "samples": 530,
                  "probability": 0.8320754716981132
                },
                {
                  "distanceBp": 3,
                  "samples": 494,
                  "probability": 0.8785425101214575
                },
                {
                  "distanceBp": 4,
                  "samples": 440,
                  "probability": 0.9113636363636364
                },
                {
                  "distanceBp": 5,
                  "samples": 365,
                  "probability": 0.9068493150684932
                },
                {
                  "distanceBp": 6,
                  "samples": 270,
                  "probability": 0.9259259259259259
                },
                {
                  "distanceBp": 7,
                  "samples": 280,
                  "probability": 0.95
                },
                {
                  "distanceBp": 8,
                  "samples": 245,
                  "probability": 0.9591836734693877
                }
              ],
              "2": [
                {
                  "distanceBp": 2,
                  "samples": 583,
                  "probability": 0.7358490566037735
                },
                {
                  "distanceBp": 3,
                  "samples": 514,
                  "probability": 0.8015564202334631
                },
                {
                  "distanceBp": 4,
                  "samples": 425,
                  "probability": 0.8305882352941176
                },
                {
                  "distanceBp": 5,
                  "samples": 354,
                  "probability": 0.8192090395480226
                },
                {
                  "distanceBp": 6,
                  "samples": 318,
                  "probability": 0.8710691823899371
                },
                {
                  "distanceBp": 7,
                  "samples": 260,
                  "probability": 0.8807692307692307
                },
                {
                  "distanceBp": 8,
                  "samples": 223,
                  "probability": 0.8789237668161435
                }
              ],
              "3": [
                {
                  "distanceBp": 2,
                  "samples": 647,
                  "probability": 0.7094281298299846
                },
                {
                  "distanceBp": 3,
                  "samples": 577,
                  "probability": 0.729636048526863
                },
                {
                  "distanceBp": 4,
                  "samples": 437,
                  "probability": 0.7437070938215103
                },
                {
                  "distanceBp": 5,
                  "samples": 376,
                  "probability": 0.8085106382978723
                },
                {
                  "distanceBp": 6,
                  "samples": 295,
                  "probability": 0.7966101694915254
                },
                {
                  "distanceBp": 7,
                  "samples": 216,
                  "probability": 0.8148148148148148
                }
              ],
              "4": [
                {
                  "distanceBp": 2,
                  "samples": 738,
                  "probability": 0.6449864498644986
                },
                {
                  "distanceBp": 3,
                  "samples": 535,
                  "probability": 0.6598130841121496
                },
                {
                  "distanceBp": 4,
                  "samples": 422,
                  "probability": 0.7132701421800948
                },
                {
                  "distanceBp": 5,
                  "samples": 330,
                  "probability": 0.7181818181818181
                },
                {
                  "distanceBp": 6,
                  "samples": 238,
                  "probability": 0.7478991596638656
                }
              ]
            }
          }
        }
      ]
    },
    {
      "asset": "sol",
      "windowCount": 210398,
      "leadingTables": [
        {
          "algoId": "vol_only_3",
          "regime": "low_vol",
          "windowShare": 0.012096122586716603,
          "avgLeadPp": 5.653420744920426,
          "surface": {
            "byRemaining": {
              "1": [
                {
                  "distanceBp": 2,
                  "samples": 212,
                  "probability": 0.7452830188679245
                }
              ],
              "2": [
                {
                  "distanceBp": 2,
                  "samples": 226,
                  "probability": 0.6637168141592921
                },
                {
                  "distanceBp": 3,
                  "samples": 215,
                  "probability": 0.7627906976744186
                }
              ],
              "3": [
                {
                  "distanceBp": 2,
                  "samples": 256,
                  "probability": 0.625
                },
                {
                  "distanceBp": 3,
                  "samples": 244,
                  "probability": 0.7172131147540983
                },
                {
                  "distanceBp": 4,
                  "samples": 220,
                  "probability": 0.7454545454545455
                }
              ],
              "4": [
                {
                  "distanceBp": 2,
                  "samples": 343,
                  "probability": 0.6005830903790087
                },
                {
                  "distanceBp": 3,
                  "samples": 262,
                  "probability": 0.6564885496183206
                },
                {
                  "distanceBp": 4,
                  "samples": 213,
                  "probability": 0.6854460093896714
                }
              ]
            }
          }
        }
      ]
    }
  ]
};
