export const OPENAI_TRADE_DECISION_CHART_WIDTH = 1600;
export const OPENAI_TRADE_DECISION_CHART_HEIGHT = 900;
export const OPENAI_TRADE_DECISION_IMAGE_DETAIL = "high";
export const OPENAI_TRADE_DECISION_REQUEST_TIMEOUT_MS = 25_000;
