import { assetSchema } from "@alea/types/assets";
import { candleSeriesSchema } from "@alea/types/candleSeries";
import { z } from "zod";

/**
 * Inside a 5-minute window, which side of the open price ("line") is the
 * spot price currently sitting on. The training pipeline calls these
 * "up"/"down" as well, so the codename matches end to end.
 */
export const leadingSideSchema = z.enum(["up", "down"]);
export type LeadingSide = z.infer<typeof leadingSideSchema>;

/**
 * Minutes left in the 5m window at the moment of the snapshot. The model
 * only knows about the four discrete in-window minute boundaries, so live
 * decisioning floors current `(windowEnd - now)` to land on one of these.
 */
export const remainingMinutesSchema = z.union([
  z.literal(1),
  z.literal(2),
  z.literal(3),
  z.literal(4),
]);
export type RemainingMinutes = z.infer<typeof remainingMinutesSchema>;

/**
 * One `(distanceBp, samples, probability)` row of the surface. `probability`
 * is the empirical share of historical snapshots in this bucket whose
 * leading side matched the eventual settlement side — i.e. the probability
 * that "the side currently in the lead at this distance with this much time
 * remaining holds to close."
 *
 * Buckets with fewer than `MIN_BUCKET_SAMPLES` observations are dropped at
 * generation time; the live lookup never sees them.
 */
export const probabilityBucketSchema = z.object({
  distanceBp: z.int().nonnegative(),
  samples: z.int().positive(),
  probability: z.number().min(0).max(1),
});
export type ProbabilityBucket = z.infer<typeof probabilityBucketSchema>;

/**
 * For one `(asset, regime)` pair, the four probability curves keyed by
 * remaining minutes. Each curve is a list of buckets sorted ascending by
 * `distanceBp` with no gaps suppressed (zero-sample buckets are simply
 * absent — this keeps the on-disk representation compact).
 */
export const probabilitySurfaceSchema = z.object({
  byRemaining: z.object({
    1: z.array(probabilityBucketSchema).readonly(),
    2: z.array(probabilityBucketSchema).readonly(),
    3: z.array(probabilityBucketSchema).readonly(),
    4: z.array(probabilityBucketSchema).readonly(),
  }),
});
export type ProbabilitySurface = z.infer<typeof probabilitySurfaceSchema>;

/**
 * One persisted (algo, regime) entry — a "leading regime table." For
 * the snapshots an algo's classifier puts into this regime, the
 * regime's hold rate sits *above* the unconditional baseline by at
 * least `LEADING_REGIME_MIN_LEAD_PP`. We persist a probability
 * surface per leading entry so the live decision evaluator can
 * iterate every (algo, regime) the snapshot fits and pick the
 * highest-edge tradeable read.
 *
 * Non-leading regimes (lagging or tie) are excluded entirely — the
 * decision evaluator skips an algo's contribution when the snapshot's
 * regime under that algo isn't in the table.
 *
 * `windowShare` is the share of all training windows the algo
 * classified into this regime (not just the leading set). It tells
 * the dashboard "how often does this regime fire" without confusing
 * the share with the across-leading-regimes total.
 *
 * `avgLeadPp` is the diagnostic figure that earned the regime its
 * leading status — sample-weighted across (remaining, distance)
 * cells. Persisted so the dashboard can show it without recomputing.
 */
export const leadingRegimeTableSchema = z.object({
  algoId: z.string(),
  regime: z.string(),
  windowShare: z.number().min(0).max(1),
  avgLeadPp: z.number(),
  surface: probabilitySurfaceSchema,
});
export type LeadingRegimeTable = z.infer<typeof leadingRegimeTableSchema>;

/**
 * Per-asset payload: an array of leading-regime tables across every
 * algo in `LIVE_TRADING_REGIME_ALGOS`, plus the total window count.
 *
 * `windowCount` is the number of *5m windows*, not snapshots; each
 * window contributes up to four snapshots (one per remaining-minute
 * slot). Every algo classifies the same windows into its own regime
 * partition, so the same window can contribute to multiple algos'
 * surfaces.
 *
 * Buckets are persisted as long as they clear `minBucketSamples`.
 */
export const assetProbabilitiesSchema = z.object({
  asset: assetSchema,
  windowCount: z.int().nonnegative(),
  leadingTables: z.array(leadingRegimeTableSchema).readonly(),
});
export type AssetProbabilities = z.infer<typeof assetProbabilitiesSchema>;

/**
 * The committed, version-controlled probability table the live runner
 * trades against. Generated by `bun alea trading:gen-probability-table`
 * from the local Postgres training data and serialized to disk under
 * `src/lib/trading/probabilityTable/`.
 *
 * Every consumer at runtime goes through `lookupProbability` rather than
 * indexing this structure directly, so the shape can evolve without
 * thrashing the call sites.
 */
export const probabilityTableSchema = z.object({
  command: z.literal("trading:gen-probability-table"),
  schemaVersion: z.literal(1),
  generatedAtMs: z.int(),
  series: candleSeriesSchema,
  /**
   * Sample-count floor used when materializing this table. Buckets below
   * this threshold were dropped. Stored on the table itself so the live
   * lookup never has to know which floor was applied.
   */
  minBucketSamples: z.int().positive(),
  /**
   * Earliest and latest 5m window-start timestamps observed across all
   * assets. Useful for sanity-checking that the table is fresh enough.
   */
  trainingRangeMs: z.object({
    firstWindowMs: z.int(),
    lastWindowMs: z.int(),
  }),
  assets: z.array(assetProbabilitiesSchema).readonly(),
});
export type ProbabilityTable = z.infer<typeof probabilityTableSchema>;
